title: AD Software Docs
description: Host for all AD software documentations.
theme: just-the-docs

url: https://ADSoftware.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
